// Rebuilds public/fonts and src/styles/fonts.css from the pinned upstream releases.
// Each face is instanced to the weights the site sets and subset to Latin, Greek,
// punctuation, super- and subscripts, arrows and maths. The OFL permits this, and none
// of the three declares a Reserved Font Name. Fallback faces carry metric overrides so
// text does not reflow when the web font swaps in.
import { createFontStack } from '@capsizecss/core';
import arial from '@capsizecss/metrics/arial';
import courierNew from '@capsizecss/metrics/courierNew';
import roboto from '@capsizecss/metrics/roboto';
import { fromFile } from '@capsizecss/unpack/fs';
import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import prettier from 'prettier';

const textRanges =
  'U+0020-007E,U+00A0-017F,U+0370-03FF,U+1D40,U+2000-206F,U+2070-209F,U+20AC,U+2122,U+2190-21FF,U+2200-22FF';
const monoRanges = `${textRanges},U+2500-257F`;

// Liberation Sans and Liberation Mono are metric-compatible with Arial and Courier New.
const extraLocalNames = {
  ArialMT: ['Liberation Sans', 'LiberationSans'],
  CourierNewPSMT: ['Liberation Mono', 'LiberationMono'],
};

const faces = [
  {
    role: 'body',
    family: 'Inter',
    release: 'https://github.com/rsms/inter/releases/download/v4.1/Inter-4.1.zip',
    source: 'web/InterVariable.woff2',
    licence: 'LICENSE.txt',
    output: 'InterVariable.woff2',
    licenceOutput: 'Inter-LICENSE.txt',
    instance: ['opsz=14', 'wght=400:700'],
    weight: '400 700',
    features: ['--layout-features+=tnum'],
    ranges: textRanges,
    fallbacks: [arial, roboto],
    generic: 'system-ui, sans-serif',
  },
  {
    role: 'heading',
    family: 'Space Grotesk',
    release:
      'https://github.com/floriankarsten/space-grotesk/releases/download/2.0.0/SpaceGrotesk-2.0.0.zip',
    source: 'SpaceGrotesk-2.0.0/woff2/SpaceGrotesk[wght].woff2',
    licence: 'SpaceGrotesk-2.0.0/OFL.txt',
    output: 'SpaceGrotesk-Variable.woff2',
    licenceOutput: 'SpaceGrotesk-LICENSE.txt',
    instance: ['wght=500:700'],
    weight: '500 700',
    features: [],
    ranges: textRanges,
    fallbacks: [arial, roboto],
    generic: 'system-ui, sans-serif',
    // Static TTFs for rendering share images at build time. Never served.
    renderCopies: [
      'SpaceGrotesk-2.0.0/ttf/static/SpaceGrotesk-Medium.ttf',
      'SpaceGrotesk-2.0.0/ttf/static/SpaceGrotesk-Bold.ttf',
    ],
  },
  {
    role: 'code',
    family: 'JetBrains Mono',
    release:
      'https://github.com/JetBrains/JetBrainsMono/releases/download/v2.304/JetBrainsMono-2.304.zip',
    source: 'fonts/webfonts/JetBrainsMono-Regular.woff2',
    licence: 'OFL.txt',
    output: 'JetBrainsMono-Regular.woff2',
    licenceOutput: 'JetBrainsMono-LICENSE.txt',
    instance: [],
    weight: '400',
    // Code sets ligatures off, so the contextual alternates that carry them are dropped.
    features: ['--layout-features-=calt'],
    ranges: monoRanges,
    fallbacks: [courierNew],
    generic: 'ui-monospace, monospace',
  },
];

const fontDir = 'public/fonts';
const renderDir = 'src/assets/og';
const work = mkdtempSync(join(tmpdir(), 'fonts-'));
mkdirSync(renderDir, { recursive: true });
// A fixed save time, since fontTools stamps instanced fonts with the current one and a
// rerun would otherwise change bytes it did not change.
const fonttools = (...args) =>
  execFileSync('uvx', ['-q', '--from', 'fonttools[woff]', ...args], {
    stdio: 'inherit',
    env: { ...process.env, SOURCE_DATE_EPOCH: '0' },
  });

try {
  const css = [
    '/* Generated by scripts/fonts.mjs. Edit that script, then run pnpm fonts. */',
  ];
  const stacks = [];

  for (const face of faces) {
    const archive = join(work, `${face.output}.zip`);
    const unpacked = join(work, face.output);
    const response = await fetch(face.release);
    if (!response.ok) throw new Error(`${face.release}: ${response.status}`);
    writeFileSync(archive, Buffer.from(await response.arrayBuffer()));
    execFileSync('python3', [
      '-c',
      'import sys, zipfile; zipfile.ZipFile(sys.argv[1]).extractall(sys.argv[2])',
      archive,
      unpacked,
    ]);

    let input = join(unpacked, face.source);
    if (face.instance.length > 0) {
      const instanced = join(work, `${face.output}.instanced`);
      fonttools(
        'fonttools',
        'varLib.instancer',
        input,
        ...face.instance,
        '-o',
        instanced,
      );
      input = instanced;
    }
    const output = join(fontDir, face.output);
    fonttools(
      'pyftsubset',
      input,
      '--flavor=woff2',
      `--unicodes=${face.ranges}`,
      ...face.features,
      `--output-file=${output}`,
    );
    copyFileSync(join(unpacked, face.licence), join(fontDir, face.licenceOutput));
    for (const copy of face.renderCopies ?? []) {
      const name = copy.split('/').pop();
      fonttools(
        'pyftsubset',
        join(unpacked, copy),
        `--unicodes=${face.ranges}`,
        '--layout-features=kern,liga',
        `--output-file=${join(renderDir, name)}`,
      );
      copyFileSync(join(unpacked, face.licence), join(renderDir, face.licenceOutput));
    }

    const metrics = { ...(await fromFile(output)), familyName: face.family };
    const { fontFamily, fontFaces } = createFontStack([metrics, ...face.fallbacks]);
    let fallbackFaces = fontFaces;
    for (const [name, extras] of Object.entries(extraLocalNames)) {
      const added = extras.map((extra) => `local('${extra}')`).join(', ');
      fallbackFaces = fallbackFaces.replace(
        `local('${name}')`,
        `local('${name}'), ${added}`,
      );
    }

    css.push(`@font-face {
  font-family: '${face.family}';
  src: url('/fonts/${face.output}') format('woff2');
  font-weight: ${face.weight};
  font-display: swap;
  unicode-range: ${face.ranges};
}`);
    css.push(fallbackFaces);
    stacks.push(`  --font-${face.role}: ${fontFamily}, ${face.generic};`);
  }

  css.push(`:root {\n${stacks.join('\n')}\n}`);
  const target = 'src/styles/fonts.css';
  const options = (await prettier.resolveConfig(target)) ?? {};
  writeFileSync(
    target,
    await prettier.format(css.join('\n\n'), { ...options, parser: 'css' }),
  );
} finally {
  rmSync(work, { recursive: true, force: true });
}
